apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: fedora-release-autotest
objects:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    name: fedora-release-autotest
  spec:
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5671
    selector:
      fedora-release-autotest: default
    sessionAffinity: ClientIP
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    generation: 1
    labels:
      app: fedora-release-autotest
    name: fedora-release-autotest
  spec:
    replicas: 1
    selector:
      fedora-release-autotest: default
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          fedora-release-autotest: default
      spec:
        containers:
        - args:
          image: fedora-release-autotest
          imagePullPolicy: Always
          name: fedora-release-autotest
          ports:
          - containerPort: 5671
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - fedora-release-autotest
        from:
          kind: ImageStreamTag
          name: fedora-release-autotest:latest
          namespace: fedora-release-autotest
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      fedora-release-autotest: default
    name: fedora-release-autotest-build
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: fedora-release-autotest:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: openshift
      git:
        ref: master
        uri: https://pagure.io/fedora-qa/fedora-release-autotest.git
      sourceSecret:
        name: gitlab-webhook
      type: Git
    strategy:
      dockerStrategy:
        noCache: true
        from:
          kind: ImageStreamTag
          name: fedora-base:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - gitlab:
        secret: gitlab-webhook
      type: GitLab
    - generic:
        secret: gitlab-webhook
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    name: fedora-release-autotest
  spec:
    host: fedora-release-autotest.apps.ocp4.prod.psi.redhat.com
    path: /
    to:
      kind: Service
      name: fedora-release-autotest
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: ImageStream
  metadata:
    generation: 1
    labels:
        app: fedora-release-autotest
    name: fedora-release-autotest
    namespace: fedora-release-autotest
  spec:
    lookupPolicy:
      local: false
